[build]
  command = "yarn deploy"
  publish = "out"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  NEXT_PUBLIC_CHEC_PUBLIC_KEY = "pk_2306936d1f32912116a05e59c515a30d39dd2ad808ac1"
